server:
  port: 9900
  tomcat:
    accept-count: 1000
    max-threads: 1000
    max-connections: 1000

zuul:
  routes:
    api-login:
      path: /client/**
      #service-id: client-service
      url: http://localhost:9906/

  host:
    socket-timeout-millis: 1000000
    connect-timeout-millis: 1000000
    max-per-route-connections: 1000
    max-total-connections: 1000
  add-host-header: true


ribbon:
  ConnectTimeout: 1000000
  ReadTimeout: 1000000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false


default_merchant: 10000000000000

token_exp: 600000 #token 失效时间

spring:
  http:
    multipart:
      max-request-size: 100Mb
      max-file-size: 100Mb
